### ISSUE TITLE
Type names includes full namespace path which makes it unreadable

### ISSUE THREAD

**Issue by Antoshidza** [elmortem/serializereferenceeditor#10]
> Problem described in title

![image](https://github.com/elmortem/serializereferenceeditor/assets/19982288/8a3559b8-6ec0-48f8-b30a-dc9100727c35)

**Comment by Red-Cat-Fat** [comment]
In general, this is the intended outcome. For a short name, the attribute `SRName` can be used.
For example:
```c#
[SRName("Draw card effect)]
public class DrawCardEffect : Effect
{
    public int Count;
}
```

**Comment by Red-Cat-Fat** [comment]
For your convenience, we have added the ability to customize the display of classes without the need for an attribute.
Look my [pull request](https://github.com/elmortem/serializereferenceeditor/pull/11)
Please wait for the @elmortem response.

**Comment by Antoshidza** [comment]
Wow, that is indeed a cool feature! It is great when code have less dependency to any framework project use!
