### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by scho** [elmortem/serializereferenceeditor#5]
Hi!
This package looks awesome and is really handy.
Do you mind adding a proper license file?

**Comment by elmortem** [comment]
I did it!

**Comment by scho** [comment]
Wow, that was fast. Thanks :)

**Comment by scho** [comment]
Could you also add a meta file? Unity now complains:
```
Asset Packages/com.elmortem.serializereferenceeditor/LICENSE.md has no meta file, but it's in an immutable folder. The asset will be ignored.
```

**Comment by scho** [comment]
Looking good, can be closed in my opinion.
